//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type AES256_GCM_SIV struct {
	nc noCopy
}

func NewAES256_GCM_SIV(key []byte) (*AES256_GCM_SIV, error) {
	return *new(*AES256_GCM_SIV), ErrNotImplemented
}

func (aes *AES256_GCM_SIV) Destroy() error { return ErrNotImplemented }

func (aes *AES256_GCM_SIV) Encrypt(plaintext, nonce, associatedData []byte) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

func (aes *AES256_GCM_SIV) Decrypt(ciphertext, nonce, associatedData []byte) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}
