//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

const BackupKeyLength = 32

type BackupKey [BackupKeyLength]byte

func (bk *BackupKey) Slice() []byte { panic(ErrNotImplemented) }

const BackupIDLength = 16

type BackupID = fixedArray16

type BackupMetadataKey = fixedArray32

type BackupMediaID = fixedArray15

type BackupMediaKey = fixedArray64

func GenerateRandomBackupKey() *BackupKey { panic(ErrNotImplemented) }

func BytesToBackupKey(bytes []byte) *BackupKey { panic(ErrNotImplemented) }

func (bk *BackupKey) DeriveBackupID(aci ServiceID) (*BackupID, error) {
	return *new(*BackupID), ErrNotImplemented
}

func (bk *BackupKey) DeriveECKey(aci ServiceID) (*PrivateKey, error) {
	return *new(*PrivateKey), ErrNotImplemented
}

func (bk *BackupKey) DeriveLocalBackupMetadataKey() (*BackupMetadataKey, error) {
	return *new(*BackupMetadataKey), ErrNotImplemented
}

func (bk *BackupKey) DeriveMediaID(mediaName string) (*BackupMediaID, error) {
	return *new(*BackupMediaID), ErrNotImplemented
}

func (bk *BackupKey) DeriveMediaEncryptionKey(mediaID *BackupMediaID) (*BackupMediaKey, error) {
	return *new(*BackupMediaKey), ErrNotImplemented
}

func (bk *BackupKey) DeriveThumbnailTransitEncryptionKey(mediaID *BackupMediaID) (*BackupMediaKey, error) {
	return *new(*BackupMediaKey), ErrNotImplemented
}
