//go:build libsignal_go

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"github.com/cwbudde/mautrix-signal/pkg/libsignalgo/signalversion"
)

const Version = signalversion.Version
