//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type CiphertextMessageType uint8

const (
	CiphertextMessageTypeWhisper   CiphertextMessageType = 2
	CiphertextMessageTypePreKey    CiphertextMessageType = 3
	CiphertextMessageTypeSenderKey CiphertextMessageType = 7
	CiphertextMessageTypePlaintext CiphertextMessageType = 8
)

type CiphertextMessage struct {
	nc noCopy
}

func NewCiphertextMessage(plaintext *PlaintextContent) (*CiphertextMessage, error) {
	return *new(*CiphertextMessage), ErrNotImplemented
}

func (c *CiphertextMessage) Destroy() error { return ErrNotImplemented }

func (c *CiphertextMessage) CancelFinalizer() {}

func (c *CiphertextMessage) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (c *CiphertextMessage) MessageType() (CiphertextMessageType, error) {
	return *new(CiphertextMessageType), ErrNotImplemented
}
