//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type DecryptionErrorMessage struct {
	nc noCopy
}

func DeserializeDecryptionErrorMessage(messageBytes []byte) (*DecryptionErrorMessage, error) {
	return *new(*DecryptionErrorMessage), ErrNotImplemented
}

func DecryptionErrorMessageForOriginalMessage(originalBytes []byte, originalType CiphertextMessageType, originalTs uint64, originalSenderDeviceID uint) (*DecryptionErrorMessage, error) {
	return *new(*DecryptionErrorMessage), ErrNotImplemented
}

func DecryptionErrorMessageFromSerializedContent(serialized []byte) (*DecryptionErrorMessage, error) {
	return *new(*DecryptionErrorMessage), ErrNotImplemented
}

func (dem *DecryptionErrorMessage) Clone() (*DecryptionErrorMessage, error) {
	return *new(*DecryptionErrorMessage), ErrNotImplemented
}

func (dem *DecryptionErrorMessage) Destroy() error { return ErrNotImplemented }

func (dem *DecryptionErrorMessage) CancelFinalizer() {}

func (dem *DecryptionErrorMessage) Serialize() ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

func (dem *DecryptionErrorMessage) GetTimestamp() (uint64, error) {
	return *new(uint64), ErrNotImplemented
}

func (dem *DecryptionErrorMessage) GetDeviceID() (uint32, error) {
	return *new(uint32), ErrNotImplemented
}

func (dem *DecryptionErrorMessage) GetRatchetKey() (*PublicKey, error) {
	return *new(*PublicKey), ErrNotImplemented
}
