//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type FingerprintVersion uint32

const (
	FingerprintVersionV1 FingerprintVersion = 1
	FingerprintVersionV2 FingerprintVersion = 2
)

type Fingerprint struct {
	nc noCopy
}

func NewFingerprint(iterations, version FingerprintVersion, localIdentifier []byte, localKey *PublicKey, remoteIdentifier []byte, remoteKey *PublicKey) (*Fingerprint, error) {
	return *new(*Fingerprint), ErrNotImplemented
}

func (f *Fingerprint) Clone() (*Fingerprint, error) { return *new(*Fingerprint), ErrNotImplemented }

func (f *Fingerprint) Destroy() error { return ErrNotImplemented }

func (f *Fingerprint) ScannableEncoding() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (f *Fingerprint) DisplayString() (string, error) { return *new(string), ErrNotImplemented }

func (f *Fingerprint) Compare(fingerprint1, fingerprint2 []byte) (bool, error) {
	return *new(bool), ErrNotImplemented
}
