//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2026 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type fixedArray15 [15]byte

type fixedArray16 [16]byte

type fixedArray17 [17]byte

type fixedArray32 [32]byte

type fixedArray64 [64]byte

type fixedArray65 [65]byte

type fixedArray97 [97]byte

type fixedArray129 [129]byte

type fixedArray153 [153]byte

type fixedArray177 [177]byte

type fixedArray289 [289]byte

type fixedArray329 [329]byte

type fixedArray409 [409]byte

type fixedArray473 [473]byte

type fixedArray497 [497]byte
