//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"time"
)

type GroupSendFullToken []byte

func (gsft GroupSendFullToken) String() string { panic(ErrNotImplemented) }

func (gsft GroupSendFullToken) CheckValidContents() error { return ErrNotImplemented }

func (gsft GroupSendFullToken) GetExpiration() (time.Time, error) {
	return *new(time.Time), ErrNotImplemented
}

type GroupSendToken []byte

func (gst GroupSendToken) CheckValidContents() error { return ErrNotImplemented }

func (gst GroupSendToken) ToFullToken(expiration time.Time) (GroupSendFullToken, error) {
	return *new(GroupSendFullToken), ErrNotImplemented
}

type GroupSendEndorsement []byte

func (gse GroupSendEndorsement) ToToken(groupSecretParams *GroupSecretParams) (GroupSendToken, error) {
	return *new(GroupSendToken), ErrNotImplemented
}

func (gse GroupSendEndorsement) ToFullToken(params *GroupSecretParams, expiration time.Time) (GroupSendFullToken, error) {
	return *new(GroupSendFullToken), ErrNotImplemented
}

func (gse GroupSendEndorsement) CheckValidContents() error { return ErrNotImplemented }

func (gse GroupSendEndorsement) Remove(other GroupSendEndorsement) (GroupSendEndorsement, error) {
	return *new(GroupSendEndorsement), ErrNotImplemented
}

func GroupSendEndorsementCombine(endorsements ...GroupSendEndorsement) (GroupSendEndorsement, error) {
	return *new(GroupSendEndorsement), ErrNotImplemented
}

type GroupSendEndorsementsResponse []byte

func (gser GroupSendEndorsementsResponse) GetExpiration() (time.Time, error) {
	return *new(time.Time), ErrNotImplemented
}

func (gser GroupSendEndorsementsResponse) CheckValidContents() error { return ErrNotImplemented }

func (gser GroupSendEndorsementsResponse) ReceiveWithServiceIDs(
	groupMembers []ServiceID, localUser ServiceID, params *GroupSecretParams, spp *ServerPublicParams,
) (GroupSendEndorsement, map[ServiceID]GroupSendEndorsement, error) {
	return *new(GroupSendEndorsement), *new(map[ServiceID]GroupSendEndorsement), ErrNotImplemented
}
