//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"github.com/google/uuid"
)

const RandomnessLength = 32

type Randomness = fixedArray32

func GenerateRandomness() Randomness { panic(ErrNotImplemented) }

const GroupMasterKeyLength = 32

const GroupIdentifierLength = 32

const GroupSecretParamsLength = 289

type GroupMasterKey [GroupMasterKeyLength]byte

type GroupSecretParams [GroupSecretParamsLength]byte

type GroupPublicParams = fixedArray97

type GroupIdentifier [GroupIdentifierLength]byte

func (gid *GroupIdentifier) String() string { panic(ErrNotImplemented) }

type UUIDCiphertext = fixedArray65

type ProfileKeyCiphertext = fixedArray65

func GenerateGroupSecretParams() (GroupSecretParams, error) {
	return *new(GroupSecretParams), ErrNotImplemented
}

func (gmk GroupMasterKey) GroupIdentifier() (*GroupIdentifier, error) {
	return *new(*GroupIdentifier), ErrNotImplemented
}

func (gmk GroupMasterKey) SecretParams() (GroupSecretParams, error) {
	return *new(GroupSecretParams), ErrNotImplemented
}

func GenerateGroupSecretParamsWithRandomness(randomness Randomness) (GroupSecretParams, error) {
	return *new(GroupSecretParams), ErrNotImplemented
}

func DeriveGroupSecretParamsFromMasterKey(groupMasterKey GroupMasterKey) (GroupSecretParams, error) {
	return *new(GroupSecretParams), ErrNotImplemented
}

func (gsp *GroupSecretParams) GetPublicParams() (*GroupPublicParams, error) {
	return *new(*GroupPublicParams), ErrNotImplemented
}

func GetGroupIdentifier(groupPublicParams GroupPublicParams) (*GroupIdentifier, error) {
	return *new(*GroupIdentifier), ErrNotImplemented
}

func (gsp *GroupSecretParams) DecryptBlobWithPadding(blob []byte) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

func (gsp *GroupSecretParams) EncryptBlobWithPaddingDeterministic(randomness Randomness, plaintext []byte, padding_len uint32) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

func (gsp *GroupSecretParams) DecryptServiceID(ciphertextServiceID UUIDCiphertext) (ServiceID, error) {
	return *new(ServiceID), ErrNotImplemented
}

func (gsp *GroupSecretParams) EncryptServiceID(serviceID ServiceID) (*UUIDCiphertext, error) {
	return *new(*UUIDCiphertext), ErrNotImplemented
}

func (gsp *GroupSecretParams) DecryptProfileKey(ciphertextProfileKey ProfileKeyCiphertext, u uuid.UUID) (*ProfileKey, error) {
	return *new(*ProfileKey), ErrNotImplemented
}

func (gsp *GroupSecretParams) EncryptProfileKey(profileKey ProfileKey, u uuid.UUID) (*ProfileKeyCiphertext, error) {
	return *new(*ProfileKeyCiphertext), ErrNotImplemented
}

func (gsp *GroupSecretParams) CreateExpiringProfileKeyCredentialPresentation(spp *ServerPublicParams, credential ExpiringProfileKeyCredential) (*ProfileKeyCredentialPresentation, error) {
	return *new(*ProfileKeyCredentialPresentation), ErrNotImplemented
}

func (gsp *GroupSecretParams) GetMasterKey() (*GroupMasterKey, error) {
	return *new(*GroupMasterKey), ErrNotImplemented
}
