//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type IdentityKey struct {
	publicKey *PublicKey
}

func NewIdentityKeyFromPublicKey(publicKey *PublicKey) (*IdentityKey, error) {
	return *new(*IdentityKey), ErrNotImplemented
}

func NewIdentityKeyFromBytes(bytes []byte) (*IdentityKey, error) {
	return *new(*IdentityKey), ErrNotImplemented
}

func (i *IdentityKey) TrySerialize() []byte { panic(ErrNotImplemented) }

func (i *IdentityKey) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func DeserializeIdentityKey(bytes []byte) (*IdentityKey, error) {
	return *new(*IdentityKey), ErrNotImplemented
}

func (i *IdentityKey) VerifyAlternateIdentity(other *IdentityKey, signature []byte) (bool, error) {
	return *new(bool), ErrNotImplemented
}

func (i *IdentityKey) Equal(other *IdentityKey) (bool, error) { return *new(bool), ErrNotImplemented }

type IdentityKeyPair struct {
	publicKey  *PublicKey
	privateKey *PrivateKey
}

func (i *IdentityKeyPair) GetPublicKey() *PublicKey { panic(ErrNotImplemented) }

func (i *IdentityKeyPair) GetPrivateKey() *PrivateKey { panic(ErrNotImplemented) }

func GenerateIdentityKeyPair() (*IdentityKeyPair, error) {
	return *new(*IdentityKeyPair), ErrNotImplemented
}

func DeserializeIdentityKeyPair(bytes []byte) (*IdentityKeyPair, error) {
	return *new(*IdentityKeyPair), ErrNotImplemented
}

func NewIdentityKeyPair(publicKey *PublicKey, privateKey *PrivateKey) (*IdentityKeyPair, error) {
	return *new(*IdentityKeyPair), ErrNotImplemented
}

func (i *IdentityKeyPair) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (i *IdentityKeyPair) GetIdentityKey() *IdentityKey { panic(ErrNotImplemented) }

func (i *IdentityKeyPair) SignAlternateIdentity(other *IdentityKey) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}
