//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Scott Weber
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"time"
)

type KyberPreKeyRecord struct {
	nc noCopy
}

type KyberKeyPair struct {
	nc noCopy
}

type KyberPublicKey struct {
	nc noCopy
}

type KyberSecretKey struct {
	nc noCopy
}

func (kp *KyberKeyPair) Destroy() error { return ErrNotImplemented }

func (kp *KyberKeyPair) CancelFinalizer() {}

func (k *KyberPublicKey) Destroy() error { return ErrNotImplemented }

func (k *KyberPublicKey) CancelFinalizer() {}

func (k *KyberSecretKey) Destroy() error { return ErrNotImplemented }

func (k *KyberSecretKey) CancelFinalizer() {}

func (kp *KyberKeyPair) GetPublicKey() (*KyberPublicKey, error) {
	return *new(*KyberPublicKey), ErrNotImplemented
}

func (kp *KyberPublicKey) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func DeserializeKyberPublicKey(serialized []byte) (*KyberPublicKey, error) {
	return *new(*KyberPublicKey), ErrNotImplemented
}

func NewKyberPreKeyRecord(id uint32, timestamp time.Time, keyPair *KyberKeyPair, signature []byte) (*KyberPreKeyRecord, error) {
	return *new(*KyberPreKeyRecord), ErrNotImplemented
}

func DeserializeKyberPreKeyRecord(serialized []byte) (*KyberPreKeyRecord, error) {
	return *new(*KyberPreKeyRecord), ErrNotImplemented
}

func (kpkr *KyberPreKeyRecord) Clone() (*KyberPreKeyRecord, error) {
	return *new(*KyberPreKeyRecord), ErrNotImplemented
}

func (kpkr *KyberPreKeyRecord) Destroy() error { return ErrNotImplemented }

func (kpkr *KyberPreKeyRecord) CancelFinalizer() {}

func (kpkr *KyberPreKeyRecord) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (kpkr *KyberPreKeyRecord) GetSignature() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (kpkr *KyberPreKeyRecord) GetID() (uint32, error) { return *new(uint32), ErrNotImplemented }

func (kpkr *KyberPreKeyRecord) GetTimestamp() (time.Time, error) {
	return *new(time.Time), ErrNotImplemented
}

func (kpkr *KyberPreKeyRecord) GetPublicKey() (*KyberPublicKey, error) {
	return *new(*KyberPublicKey), ErrNotImplemented
}

func (kpkr *KyberPreKeyRecord) GetSecretKey() (*KyberSecretKey, error) {
	return *new(*KyberSecretKey), ErrNotImplemented
}

func KyberKeyPairGenerate() (*KyberKeyPair, error) { return *new(*KyberKeyPair), ErrNotImplemented }
