//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type MessageBackupKey struct {
	nc noCopy
}

const MessageBackupKeyBytesLength = 32

type messageBackupKeyBytes = fixedArray32

func MessageBackupKeyFromAccountEntropyPool(aep AccountEntropyPool, aci ServiceID) (*MessageBackupKey, error) {
	return *new(*MessageBackupKey), ErrNotImplemented
}

func MessageBackupKeyFromBackupKeyAndID(backupKey *BackupKey, backupID *BackupID) (*MessageBackupKey, error) {
	return *new(*MessageBackupKey), ErrNotImplemented
}

func (bk *MessageBackupKey) Destroy() error { return ErrNotImplemented }

func (bk *MessageBackupKey) GetHMACKey() ([MessageBackupKeyBytesLength]byte, error) {
	return *new([MessageBackupKeyBytesLength]byte), ErrNotImplemented
}

func (bk *MessageBackupKey) GetAESKey() ([MessageBackupKeyBytesLength]byte, error) {
	return *new([MessageBackupKeyBytesLength]byte), ErrNotImplemented
}
