//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"context"
)

func Encrypt(ctx context.Context, plaintext []byte, forAddress, localAddress *Address, sessionStore SessionStore, identityKeyStore IdentityKeyStore) (*CiphertextMessage, error) {
	return *new(*CiphertextMessage), ErrNotImplemented
}

func Decrypt(ctx context.Context, message *Message, fromAddress, localAddress *Address, sessionStore SessionStore, identityStore IdentityKeyStore) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

type Message struct {
	nc noCopy
}

func DeserializeMessage(serialized []byte) (*Message, error) {
	return *new(*Message), ErrNotImplemented
}

func (m *Message) Clone() (*Message, error) { return *new(*Message), ErrNotImplemented }

func (m *Message) Destroy() error { return ErrNotImplemented }

func (m *Message) CancelFinalizer() {}

func (m *Message) GetBody() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (m *Message) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (m *Message) GetMessageVersion() (uint32, error) { return *new(uint32), ErrNotImplemented }

func (m *Message) GetCounter() (uint32, error) { return *new(uint32), ErrNotImplemented }
