//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"context"
)

func DecryptPreKey(ctx context.Context, preKeyMessage *PreKeyMessage, fromAddress, localAddress *Address, sessionStore SessionStore, identityStore IdentityKeyStore, preKeyStore PreKeyStore, signedPreKeyStore SignedPreKeyStore, kyberPreKeyStore KyberPreKeyStore) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

type PreKeyRecord struct {
	nc noCopy
}

func NewPreKeyRecord(id uint32, publicKey *PublicKey, privateKey *PrivateKey) (*PreKeyRecord, error) {
	return *new(*PreKeyRecord), ErrNotImplemented
}

func NewPreKeyRecordFromPrivateKey(id uint32, privateKey *PrivateKey) (*PreKeyRecord, error) {
	return *new(*PreKeyRecord), ErrNotImplemented
}

func DeserializePreKeyRecord(serialized []byte) (*PreKeyRecord, error) {
	return *new(*PreKeyRecord), ErrNotImplemented
}

func (pkr *PreKeyRecord) Clone() (*PreKeyRecord, error) {
	return *new(*PreKeyRecord), ErrNotImplemented
}

func (pkr *PreKeyRecord) Destroy() error { return ErrNotImplemented }

func (pkr *PreKeyRecord) CancelFinalizer() {}

func (pkr *PreKeyRecord) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (pkr *PreKeyRecord) GetID() (uint32, error) { return *new(uint32), ErrNotImplemented }

func (pkr *PreKeyRecord) GetPublicKey() (*PublicKey, error) {
	return *new(*PublicKey), ErrNotImplemented
}

func (pkr *PreKeyRecord) GetPrivateKey() (*PrivateKey, error) {
	return *new(*PrivateKey), ErrNotImplemented
}
