//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type PreKeyMessage struct {
	nc noCopy
}

func DeserializePreKeyMessage(serialized []byte) (*PreKeyMessage, error) {
	return *new(*PreKeyMessage), ErrNotImplemented
}

func (m *PreKeyMessage) Clone() (*PreKeyMessage, error) {
	return *new(*PreKeyMessage), ErrNotImplemented
}

func (m *PreKeyMessage) Destroy() error { return ErrNotImplemented }

func (m *PreKeyMessage) CancelFinalizer() {}

func (m *PreKeyMessage) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (m *PreKeyMessage) GetVersion() (uint32, error) { return *new(uint32), ErrNotImplemented }

func (m *PreKeyMessage) GetRegistrationID() (uint32, error) { return *new(uint32), ErrNotImplemented }

func (m *PreKeyMessage) GetPreKeyID() (*uint32, error) { return *new(*uint32), ErrNotImplemented }

func (m *PreKeyMessage) GetSignedPreKeyID() (uint32, error) { return *new(uint32), ErrNotImplemented }

func (m *PreKeyMessage) GetBaseKey() (*PublicKey, error) { return *new(*PublicKey), ErrNotImplemented }

func (m *PreKeyMessage) GetIdentityKey() (*IdentityKey, error) {
	return *new(*IdentityKey), ErrNotImplemented
}

func (m *PreKeyMessage) GetSignalMessage() (*Message, error) {
	return *new(*Message), ErrNotImplemented
}
