//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type PrivateKey struct {
	nc noCopy
}

func GeneratePrivateKey() (*PrivateKey, error) { return *new(*PrivateKey), ErrNotImplemented }

func DeserializePrivateKey(keyData []byte) (*PrivateKey, error) {
	return *new(*PrivateKey), ErrNotImplemented
}

func (pk *PrivateKey) Clone() (*PrivateKey, error) { return *new(*PrivateKey), ErrNotImplemented }

func (pk *PrivateKey) Destroy() error { return ErrNotImplemented }

func (pk *PrivateKey) CancelFinalizer() {}

func (pk *PrivateKey) GetPublicKey() (*PublicKey, error) { return *new(*PublicKey), ErrNotImplemented }

func (pk *PrivateKey) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (pk *PrivateKey) Sign(message []byte) ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (pk *PrivateKey) Agree(publicKey *PublicKey) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}
