//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type PublicKey struct {
	nc noCopy
}

func (pk *PublicKey) Clone() (*PublicKey, error) { return *new(*PublicKey), ErrNotImplemented }

func DeserializePublicKey(keyData []byte) (*PublicKey, error) {
	return *new(*PublicKey), ErrNotImplemented
}

func (pk *PublicKey) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (k *PublicKey) Destroy() error { return ErrNotImplemented }

func (k *PublicKey) CancelFinalizer() {}

func (k *PublicKey) Equal(other *PublicKey) (bool, error) { return *new(bool), ErrNotImplemented }

func (k *PublicKey) Bytes() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (k *PublicKey) Verify(message, signature []byte) (bool, error) {
	return *new(bool), ErrNotImplemented
}
