//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Scott Weber
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"context"
	"github.com/google/uuid"
)

type SealedSenderAddress struct {
	E164     string
	UUID     uuid.UUID
	DeviceID uint32
}

func NewSealedSenderAddress(e164 string, uuid uuid.UUID, deviceID uint32) *SealedSenderAddress {
	panic(ErrNotImplemented)
}

func SealedSenderEncryptPlaintext(
	ctx context.Context,
	message []byte,
	contentHint UnidentifiedSenderMessageContentHint,
	forAddress, localAddress *Address,
	fromSenderCert *SenderCertificate,
	sessionStore SessionStore,
	identityStore IdentityKeyStore,
	groupID *GroupIdentifier,
) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

func SealedSenderEncrypt(ctx context.Context, usmc *UnidentifiedSenderMessageContent, forRecipient *Address, identityStore IdentityKeyStore) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

type SessionAddressTuple struct {
	ServiceID ServiceID
	DeviceID  int
	Address   *Address
	Record    *SessionRecord
}

func SealedSenderMultiRecipientEncrypt(
	ctx context.Context,
	usmc *UnidentifiedSenderMessageContent,
	recipients []SessionAddressTuple,
	identityStore IdentityKeyStore,
) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

type SealedSenderResult struct {
	Message []byte
	Sender  SealedSenderAddress
}

func SealedSenderDecryptToUSMC(
	ctx context.Context,
	ciphertext []byte,
	identityStore IdentityKeyStore,
) (*UnidentifiedSenderMessageContent, error) {
	return *new(*UnidentifiedSenderMessageContent), ErrNotImplemented
}

type UnidentifiedSenderMessageContentHint uint32

const (
	UnidentifiedSenderMessageContentHintDefault    UnidentifiedSenderMessageContentHint = 0
	UnidentifiedSenderMessageContentHintResendable UnidentifiedSenderMessageContentHint = 1
	UnidentifiedSenderMessageContentHintImplicit   UnidentifiedSenderMessageContentHint = 2
)

func (hint UnidentifiedSenderMessageContentHint) String() string { panic(ErrNotImplemented) }

type UnidentifiedSenderMessageContent struct {
	nc noCopy
}

func NewUnidentifiedSenderMessageContent(message *CiphertextMessage, senderCertificate *SenderCertificate, contentHint UnidentifiedSenderMessageContentHint, groupID *GroupIdentifier) (*UnidentifiedSenderMessageContent, error) {
	return *new(*UnidentifiedSenderMessageContent), ErrNotImplemented
}

func DeserializeUnidentifiedSenderMessageContent(serialized []byte) (*UnidentifiedSenderMessageContent, error) {
	return *new(*UnidentifiedSenderMessageContent), ErrNotImplemented
}

func (usmc *UnidentifiedSenderMessageContent) Destroy() error { return ErrNotImplemented }

func (usmc *UnidentifiedSenderMessageContent) CancelFinalizer() {}

func (usmc *UnidentifiedSenderMessageContent) Serialize() ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

func (usmc *UnidentifiedSenderMessageContent) GetContents() ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

func (usmc *UnidentifiedSenderMessageContent) GetGroupID() (*GroupIdentifier, error) {
	return *new(*GroupIdentifier), ErrNotImplemented
}

func (usmc *UnidentifiedSenderMessageContent) GetSenderCertificate() (*SenderCertificate, error) {
	return *new(*SenderCertificate), ErrNotImplemented
}

func (usmc *UnidentifiedSenderMessageContent) GetMessageType() (CiphertextMessageType, error) {
	return *new(CiphertextMessageType), ErrNotImplemented
}

func (usmc *UnidentifiedSenderMessageContent) GetContentHint() (UnidentifiedSenderMessageContentHint, error) {
	return *new(UnidentifiedSenderMessageContentHint), ErrNotImplemented
}
