//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"github.com/google/uuid"
	"time"
)

type SenderCertificate struct {
	nc noCopy
}

// NewSenderCertificate should only be used for testing (at least according to
// the Swift bindings).
func NewSenderCertificate(sender *SealedSenderAddress, publicKey *PublicKey, expiration time.Time, signerCertificate *ServerCertificate, signerKey *PrivateKey) (*SenderCertificate, error) {
	return *new(*SenderCertificate), ErrNotImplemented
}

func DeserializeSenderCertificate(serialized []byte) (*SenderCertificate, error) {
	return *new(*SenderCertificate), ErrNotImplemented
}

func (sc *SenderCertificate) Clone() (*SenderCertificate, error) {
	return *new(*SenderCertificate), ErrNotImplemented
}

func (sc *SenderCertificate) Destroy() error { return ErrNotImplemented }

func (sc *SenderCertificate) CancelFinalizer() {}

func (sc *SenderCertificate) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (sc *SenderCertificate) GetCertificate() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (sc *SenderCertificate) GetSignature() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (sc *SenderCertificate) GetSenderUUID() (uuid.UUID, error) {
	return *new(uuid.UUID), ErrNotImplemented
}

func (sc *SenderCertificate) GetSenderE164() (string, error) { return *new(string), ErrNotImplemented }

func (sc *SenderCertificate) GetExpiration() (time.Time, error) {
	return *new(time.Time), ErrNotImplemented
}

func (sc *SenderCertificate) GetDeviceID() (uint32, error) { return *new(uint32), ErrNotImplemented }

func (sc *SenderCertificate) GetKey() (*PublicKey, error) { return *new(*PublicKey), ErrNotImplemented }

func (sc *SenderCertificate) Validate(trustRoots []*PublicKey, ts time.Time) (bool, error) {
	return *new(bool), ErrNotImplemented
}

func (sc *SenderCertificate) GetServerCertificate() (*ServerCertificate, error) {
	return *new(*ServerCertificate), ErrNotImplemented
}
