//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

type ServerCertificate struct {
	nc noCopy
}

// NewServerCertificate should only be used for testing (at least according to
// the Swift bindings).
func NewServerCertificate(keyID uint32, publicKey *PublicKey, trustRoot *PrivateKey) (*ServerCertificate, error) {
	return *new(*ServerCertificate), ErrNotImplemented
}

func DeserializeServerCertificate(serialized []byte) (*ServerCertificate, error) {
	return *new(*ServerCertificate), ErrNotImplemented
}

func (sc *ServerCertificate) Clone() (*ServerCertificate, error) {
	return *new(*ServerCertificate), ErrNotImplemented
}

func (sc *ServerCertificate) Destroy() error { return ErrNotImplemented }

func (sc *ServerCertificate) CancelFinalizer() {}

func (sc *ServerCertificate) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (sc *ServerCertificate) GetCertificate() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (sc *ServerCertificate) GetSignature() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (sc *ServerCertificate) GetKeyID() (uint32, error) { return *new(uint32), ErrNotImplemented }

func (sc *ServerCertificate) GetKey() (*PublicKey, error) { return *new(*PublicKey), ErrNotImplemented }
