//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2024 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"database/sql/driver"
	"github.com/google/uuid"
	"github.com/rs/zerolog"
)

type ServiceIDType byte

const (
	ServiceIDTypeACI ServiceIDType = 0
	ServiceIDTypePNI ServiceIDType = 1
)

func (st ServiceIDType) String() string { panic(ErrNotImplemented) }

func (st ServiceIDType) GoString() string { panic(ErrNotImplemented) }

type ServiceID struct {
	Type ServiceIDType
	UUID uuid.UUID
}

var EmptyServiceID ServiceID

func NewPNIServiceID(uuid uuid.UUID) ServiceID { panic(ErrNotImplemented) }

func NewACIServiceID(uuid uuid.UUID) ServiceID { panic(ErrNotImplemented) }

func (s ServiceID) ToACIAndPNI() (aci, pni uuid.UUID) { panic(ErrNotImplemented) }

func (s ServiceID) IsEmpty() bool { panic(ErrNotImplemented) }

func (s ServiceID) Address(deviceID uint) (*Address, error) { return *new(*Address), ErrNotImplemented }

func (s ServiceID) Bytes() []byte { panic(ErrNotImplemented) }

func (s ServiceID) Value() (driver.Value, error) { return *new(driver.Value), ErrNotImplemented }

func (s ServiceID) String() string { panic(ErrNotImplemented) }

func (s ServiceID) GoString() string { panic(ErrNotImplemented) }

func (s ServiceID) MarshalText() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (s *ServiceID) UnmarshalText(text []byte) error { return ErrNotImplemented }

func (s ServiceID) MarshalZerologObject(e *zerolog.Event) {}

const ServiceIDUUIDLength = 16

const ServiceIDFixedBytesLength = 17

type ServiceIDFixedBytes = fixedArray17

func (s ServiceID) FixedBytes() *ServiceIDFixedBytes { panic(ErrNotImplemented) }

func ServiceIDFromString(val string) (ServiceID, error) { return *new(ServiceID), ErrNotImplemented }

func ServiceIDFromBytes(bytes []byte) (ServiceID, error) { return *new(ServiceID), ErrNotImplemented }
