//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2024 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"time"
)

type SGXClientState struct {
	nc noCopy
}

func NewCDS2ClientState(mrenclave, attestationMessage []byte, currentTime time.Time) (*SGXClientState, error) {
	return *new(*SGXClientState), ErrNotImplemented
}

func (cds *SGXClientState) Destroy() error { return ErrNotImplemented }

func (cds *SGXClientState) InitialRequest() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (cds *SGXClientState) CompleteHandshake(handshakeReceived []byte) error {
	return ErrNotImplemented
}

func (cds *SGXClientState) EstablishedSend(plaintext []byte) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

func (cds *SGXClientState) EstablishedReceive(ciphertext []byte) ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}
