//go:build purego

// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2023 Sumner Evans
// Copyright (C) 2025 Tulir Asokan
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by stubgen; DO NOT EDIT.

package libsignalgo

import (
	"time"
)

type SignedPreKeyRecord struct {
	nc noCopy
}

func NewSignedPreKeyRecord(id uint32, timestamp time.Time, publicKey *PublicKey, privateKey *PrivateKey, signature []byte) (*SignedPreKeyRecord, error) {
	return *new(*SignedPreKeyRecord), ErrNotImplemented
}

func NewSignedPreKeyRecordFromPrivateKey(id uint32, timestamp time.Time, privateKey *PrivateKey, signature []byte) (*SignedPreKeyRecord, error) {
	return *new(*SignedPreKeyRecord), ErrNotImplemented
}

func DeserializeSignedPreKeyRecord(serialized []byte) (*SignedPreKeyRecord, error) {
	return *new(*SignedPreKeyRecord), ErrNotImplemented
}

func (spkr *SignedPreKeyRecord) Clone() (*SignedPreKeyRecord, error) {
	return *new(*SignedPreKeyRecord), ErrNotImplemented
}

func (spkr *SignedPreKeyRecord) Destroy() error { return ErrNotImplemented }

func (spkr *SignedPreKeyRecord) CancelFinalizer() {}

func (spkr *SignedPreKeyRecord) Serialize() ([]byte, error) { return *new([]byte), ErrNotImplemented }

func (spkr *SignedPreKeyRecord) GetSignature() ([]byte, error) {
	return *new([]byte), ErrNotImplemented
}

func (spkr *SignedPreKeyRecord) GetID() (uint32, error) { return *new(uint32), ErrNotImplemented }

func (spkr *SignedPreKeyRecord) GetTimestamp() (time.Time, error) {
	return *new(time.Time), ErrNotImplemented
}

func (spkr *SignedPreKeyRecord) GetPublicKey() (*PublicKey, error) {
	return *new(*PublicKey), ErrNotImplemented
}

func (spkr *SignedPreKeyRecord) GetPrivateKey() (*PrivateKey, error) {
	return *new(*PrivateKey), ErrNotImplemented
}
