// mautrix-signal - A Matrix-signal puppeting bridge.
// Copyright (C) 2026 Christian Budde
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Command stubgen maintains the purego build of libsignalgo.
//
// Every cgo file x.go in libsignalgo is built with `!libsignal_go`. Its purego counterpart is
// x_purego.go (build tag `libsignal_go`), which declares the same exported API.
//
//	go run ./pkg/libsignalgo/internal/stubgen -gen x.go ...   # write stub twins for cgo files
//	go run ./pkg/libsignalgo/internal/stubgen -check          # compare the exported API of both builds
//
// -gen adds `//go:build !libsignal_go` to the cgo file and writes x_purego.go with the file's constants,
// types (fields with C types dropped) and exported functions and methods. Stub bodies return
// ErrNotImplemented when the function returns an error, do nothing when it has no results, and
// panic otherwise. A stub file stops being generated once it's hand-written: -gen refuses to
// overwrite a file that doesn't carry the generated marker.
//
// -check parses the package twice, once per build, and fails when an exported identifier or
// signature differs. Struct fields aren't compared, since they differ by design, and types that
// wrap a C type count as structs. Exported functions with C types in their signature (the cgo
// buffer helpers) can't be called from outside the package and exist only in the cgo build.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/build/constraint"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const generatedMarker = "// Code generated by stubgen; DO NOT EDIT."

func main() {
	dir := flag.String("dir", "pkg/libsignalgo", "libsignalgo package directory")
	gen := flag.Bool("gen", false, "generate purego stubs for the given cgo files (all when none are given)")
	check := flag.Bool("check", false, "compare the exported API of the cgo and purego builds")
	flag.Parse()

	var err error
	switch {
	case *gen:
		err = generate(*dir, flag.Args())
	case *check:
		err = checkAPI(*dir)
	default:
		flag.Usage()
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "stubgen:", err)
		os.Exit(1)
	}
}

// generate

func generate(dir string, names []string) error {
	if len(names) == 0 {
		all, err := filepath.Glob(filepath.Join(dir, "*.go"))
		if err != nil {
			return err
		}
		for _, path := range all {
			names = append(names, filepath.Base(path))
		}
	}
	for _, name := range names {
		if strings.HasSuffix(name, "_purego.go") {
			continue
		}
		path := filepath.Join(dir, filepath.Base(name))
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, src, parser.ParseComments)
		if err != nil {
			return err
		}
		// Tests are left alone: a test runs in both builds unless it carries its
		// own `//go:build !libsignal_go` (set by hand for tests of code the purego build
		// doesn't implement yet).
		if strings.HasSuffix(name, "_test.go") || !importsC(file) {
			continue
		}
		expr, hasConstraint := buildConstraint(file)
		if !strings.Contains(expr, "libsignal_go") {
			err = addConstraint(path, src, file, expr, hasConstraint)
			if err != nil {
				return err
			}
		}
		// Only a constraint of the file's own (not the one added here) marks it as special.
		// Files with their own constraint (the compiler-specific fixedarray files) hold no
		// exported API, see -check.
		if hasConstraint && expr != "!libsignal_go" {
			continue
		}
		out, err := stubFile(fset, file)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		target := strings.TrimSuffix(path, ".go") + "_purego.go"
		old, err := os.ReadFile(target)
		if err == nil && !bytes.Contains(old, []byte(generatedMarker)) {
			continue // hand-written; -check still compares its API
		}
		err = os.WriteFile(target, out, 0o644)
		if err != nil {
			return err
		}
	}
	return nil
}

func importsC(file *ast.File) bool {
	for _, imp := range file.Imports {
		if imp.Path.Value == `"C"` {
			return true
		}
	}
	return false
}

func buildConstraint(file *ast.File) (string, bool) {
	for _, group := range file.Comments {
		if group.Pos() >= file.Package {
			break
		}
		for _, c := range group.List {
			if constraint.IsGoBuild(c.Text) {
				return strings.TrimSpace(strings.TrimPrefix(c.Text, "//go:build")), true
			}
		}
	}
	return "", false
}

// addConstraint makes the cgo file (or test) build only without the libsignal_go tag.
func addConstraint(path string, src []byte, file *ast.File, expr string, has bool) error {
	text := string(src)
	if has {
		old := "//go:build " + expr
		text = strings.Replace(text, old, "//go:build !libsignal_go && ("+expr+")", 1)
	} else {
		// Put the constraint before the package clause, after any leading license header.
		offset := 0
		if file.Doc != nil {
			offset = int(file.Doc.Pos()) - 1
		} else {
			offset = int(file.Package) - 1
		}
		text = text[:offset] + "//go:build !libsignal_go\n\n" + text[offset:]
	}
	return os.WriteFile(path, []byte(text), 0o644)
}

func stubFile(fset *token.FileSet, file *ast.File) ([]byte, error) {
	var decls []ast.Decl
	cmap := ast.NewCommentMap(fset, file, file.Comments)
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			if out := stubGenDecl(d); out != nil {
				decls = append(decls, out)
			}
		case *ast.FuncDecl:
			if out := stubFunc(d); out != nil {
				decls = append(decls, out)
			}
		}
	}

	var buf bytes.Buffer
	buf.WriteString("//go:build libsignal_go\n\n")
	buf.WriteString(licenseHeader(file))
	buf.WriteString(generatedMarker + "\n\n")
	buf.WriteString("package " + file.Name.Name + "\n\n")

	body := &ast.File{Name: file.Name, Decls: decls}
	body.Comments = docComments(cmap, decls)
	var declBuf bytes.Buffer
	cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	for _, decl := range decls {
		err := cfg.Fprint(&declBuf, fset, &printer.CommentedNode{Node: decl, Comments: body.Comments})
		if err != nil {
			return nil, err
		}
		declBuf.WriteString("\n\n")
	}
	imports := usedImports(file, declBuf.String())
	if len(imports) > 0 {
		// Grouped like `goimports -local github.com/cwbudde/mautrix-signal` (the repo's pre-commit hook):
		// standard library, third party, this module.
		buf.WriteString("import (\n")
		for i, group := range groupImports(imports) {
			if i > 0 {
				buf.WriteString("\n")
			}
			for _, imp := range group {
				buf.WriteString("\t" + imp + "\n")
			}
		}
		buf.WriteString(")\n\n")
	}
	buf.Write(declBuf.Bytes())
	return format.Source(buf.Bytes())
}

func licenseHeader(file *ast.File) string {
	var sb strings.Builder
	for _, group := range file.Comments {
		if group.Pos() >= file.Package || (file.Doc != nil && group == file.Doc) {
			break
		}
		skip := false
		for _, c := range group.List {
			if constraint.IsGoBuild(c.Text) {
				skip = true
			}
		}
		if skip {
			continue
		}
		for _, c := range group.List {
			sb.WriteString(c.Text + "\n")
		}
		sb.WriteString("\n")
	}
	return sb.String()
}

// docComments keeps the doc comments of the retained declarations; comments inside the replaced
// function bodies are dropped.
func docComments(cmap ast.CommentMap, decls []ast.Decl) []*ast.CommentGroup {
	var groups []*ast.CommentGroup
	add := func(g *ast.CommentGroup) {
		if g != nil {
			groups = append(groups, g)
		}
	}
	for _, decl := range decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			add(d.Doc)
		case *ast.GenDecl:
			add(d.Doc)
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					add(s.Doc)
					add(s.Comment)
				case *ast.ValueSpec:
					add(s.Doc)
					add(s.Comment)
				}
			}
		}
	}
	_ = cmap
	sort.Slice(groups, func(i, j int) bool { return groups[i].Pos() < groups[j].Pos() })
	return groups
}

func usedImports(file *ast.File, code string) []string {
	var out []string
	for _, imp := range file.Imports {
		path, _ := strconv.Unquote(imp.Path.Value)
		if path == "C" {
			continue
		}
		name := filepath.Base(path)
		if imp.Name != nil {
			name = imp.Name.Name
		}
		if name == "_" || !strings.Contains(code, name+".") {
			continue
		}
		spec := imp.Path.Value
		if imp.Name != nil {
			spec = imp.Name.Name + " " + spec
		}
		out = append(out, spec)
	}
	return out
}

const localPrefix = "github.com/cwbudde/mautrix-signal"

func groupImports(specs []string) [][]string {
	var std, third, local []string
	for _, spec := range specs {
		path, _ := strconv.Unquote(spec[strings.Index(spec, `"`):])
		switch {
		case strings.HasPrefix(path, localPrefix):
			local = append(local, spec)
		case !strings.Contains(strings.Split(path, "/")[0], "."):
			std = append(std, spec)
		default:
			third = append(third, spec)
		}
	}
	var groups [][]string
	for _, group := range [][]string{std, third, local} {
		if len(group) > 0 {
			sort.Strings(group)
			groups = append(groups, group)
		}
	}
	return groups
}

func refersToC(node ast.Node) bool {
	found := false
	ast.Inspect(node, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok && id.Name == "C" {
				found = true
			}
		}
		return !found
	})
	return found
}

func stubGenDecl(d *ast.GenDecl) ast.Decl {
	if d.Tok == token.IMPORT {
		return nil
	}
	var specs []ast.Spec
	for _, spec := range d.Specs {
		switch s := spec.(type) {
		case *ast.ValueSpec:
			if refersToC(s) {
				continue
			}
			if d.Tok == token.VAR {
				// Only exported, explicitly typed variables are API; initializers may call into C.
				if s.Type == nil || !anyExported(s.Names) {
					continue
				}
				s.Values = nil
			}
			specs = append(specs, s)
		case *ast.TypeSpec:
			specs = append(specs, stubType(s))
		}
	}
	if len(specs) == 0 {
		return nil
	}
	d.Specs = specs
	if len(specs) == 1 && d.Tok != token.CONST {
		d.Lparen = token.NoPos
	}
	return d
}

func anyExported(names []*ast.Ident) bool {
	for _, n := range names {
		if n.IsExported() {
			return true
		}
	}
	return false
}

func stubType(s *ast.TypeSpec) *ast.TypeSpec {
	if st, ok := s.Type.(*ast.StructType); ok {
		var fields []*ast.Field
		for _, f := range st.Fields.List {
			if !refersToC(f.Type) {
				fields = append(fields, f)
			}
		}
		st.Fields.List = fields
		return s
	}
	if refersToC(s.Type) {
		// An opaque C handle (often an alias of the C struct) becomes a distinct Go struct.
		s.Assign = token.NoPos
		s.Type = &ast.StructType{Fields: &ast.FieldList{}}
	}
	return s
}

func stubFunc(d *ast.FuncDecl) ast.Decl {
	if !d.Name.IsExported() || refersToC(d.Type) || (d.Recv != nil && refersToC(d.Recv)) {
		return nil
	}
	if d.Recv != nil && !receiverExported(d.Recv) {
		return nil
	}
	d.Body = &ast.BlockStmt{List: stubBody(d.Type.Results)}
	return d
}

func receiverExported(recv *ast.FieldList) bool {
	t := recv.List[0].Type
	if star, ok := t.(*ast.StarExpr); ok {
		t = star.X
	}
	if idx, ok := t.(*ast.IndexExpr); ok {
		t = idx.X
	}
	id, ok := t.(*ast.Ident)
	return ok && id.IsExported()
}

func stubBody(results *ast.FieldList) []ast.Stmt {
	errNotImpl := ast.NewIdent("ErrNotImplemented")
	if results == nil || len(results.List) == 0 {
		return nil
	}
	var types []ast.Expr
	for _, f := range results.List {
		n := len(f.Names)
		if n == 0 {
			n = 1
		}
		for range n {
			types = append(types, f.Type)
		}
	}
	last, ok := types[len(types)-1].(*ast.Ident)
	if !ok || last.Name != "error" {
		return []ast.Stmt{&ast.ExprStmt{X: &ast.CallExpr{
			Fun:  ast.NewIdent("panic"),
			Args: []ast.Expr{errNotImpl},
		}}}
	}
	var values []ast.Expr
	for _, t := range types[:len(types)-1] {
		values = append(values, &ast.StarExpr{X: &ast.CallExpr{
			Fun:  ast.NewIdent("new"),
			Args: []ast.Expr{t},
		}})
	}
	values = append(values, errNotImpl)
	return []ast.Stmt{&ast.ReturnStmt{Results: values}}
}

// check

func checkAPI(dir string) error {
	cgoAPI, err := exportedAPI(dir, false)
	if err != nil {
		return err
	}
	pureAPI, err := exportedAPI(dir, true)
	if err != nil {
		return err
	}
	var diffs []string
	for key := range cgoAPI {
		if !pureAPI[key] {
			diffs = append(diffs, "missing in purego: "+key)
		}
	}
	for key := range pureAPI {
		if !cgoAPI[key] {
			diffs = append(diffs, "only in purego:    "+key)
		}
	}
	if len(diffs) > 0 {
		sort.Strings(diffs)
		return fmt.Errorf("exported API differs between the builds:\n  %s", strings.Join(diffs, "\n  "))
	}
	fmt.Printf("stubgen: %d exported declarations match\n", len(cgoAPI))
	return nil
}

// exportedAPI returns one key per exported declaration of the package as built with or without
// the libsignal_go tag (for linux/gc; compiler-specific files must not declare exported API).
func exportedAPI(dir string, purego bool) (map[string]bool, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, err
	}
	api := map[string]bool{}
	fset := token.NewFileSet()
	for _, path := range paths {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		expr, has := buildConstraint(file)
		if has {
			x, err := constraint.Parse("//go:build " + expr)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", path, err)
			}
			ok := x.Eval(func(tag string) bool {
				switch tag {
				case "libsignal_go":
					return purego
				case "cgo":
					return !purego
				case "linux", "unix", "gc", "amd64":
					return true
				}
				return false
			})
			if !ok {
				continue
			}
		}
		for _, decl := range file.Decls {
			for _, key := range declKeys(fset, decl) {
				api[key] = true
			}
		}
	}
	return api, nil
}

func declKeys(fset *token.FileSet, decl ast.Decl) []string {
	var keys []string
	switch d := decl.(type) {
	case *ast.FuncDecl:
		if !d.Name.IsExported() || refersToC(d.Type) {
			return nil
		}
		prefix := "func "
		if d.Recv != nil {
			if !receiverExported(d.Recv) {
				return nil
			}
			prefix += "(" + nodeString(fset, d.Recv.List[0].Type) + ") "
		}
		keys = append(keys, prefix+d.Name.Name+strings.TrimPrefix(nodeString(fset, stripNames(d.Type)), "func"))
	case *ast.GenDecl:
		for _, spec := range d.Specs {
			switch s := spec.(type) {
			case *ast.TypeSpec:
				if !s.Name.IsExported() {
					continue
				}
				kind := "type " + s.Name.Name
				switch t := s.Type.(type) {
				case *ast.StructType:
					kind += " struct"
				case *ast.SelectorExpr, *ast.StarExpr:
					if refersToC(t) {
						kind += " struct"
					} else {
						kind += " " + nodeString(fset, t)
					}
				case *ast.InterfaceType:
					kind += " " + nodeString(fset, t)
				default:
					kind += " " + nodeString(fset, t)
				}
				keys = append(keys, kind)
			case *ast.ValueSpec:
				for i, name := range s.Names {
					if !name.IsExported() {
						continue
					}
					key := d.Tok.String() + " " + name.Name
					if s.Type != nil {
						key += " " + nodeString(fset, s.Type)
					}
					if d.Tok == token.CONST && i < len(s.Values) {
						key += " = " + nodeString(fset, s.Values[i])
					}
					keys = append(keys, key)
				}
			}
		}
	}
	return keys
}

// stripNames drops parameter and result names, which aren't part of the API.
func stripNames(ft *ast.FuncType) *ast.FuncType {
	strip := func(fl *ast.FieldList) *ast.FieldList {
		if fl == nil {
			return nil
		}
		out := &ast.FieldList{}
		for _, f := range fl.List {
			n := len(f.Names)
			if n == 0 {
				n = 1
			}
			for range n {
				out.List = append(out.List, &ast.Field{Type: f.Type})
			}
		}
		return out
	}
	return &ast.FuncType{TypeParams: ft.TypeParams, Params: strip(ft.Params), Results: strip(ft.Results)}
}

func nodeString(fset *token.FileSet, node ast.Node) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, fset, node)
	return strings.Join(strings.Fields(buf.String()), " ")
}
